### PR TITLE
Add new advance checker: blank-import

### PR DESCRIPTION
**Pull request by hendrywiranto**
## Summary
Add new advance checker: `blank-import`

## Motivation
As stated in the issue:
> Import of testify packages (assert, require, suite, mock, http) as _ is useless: those package don't do init magic.

## Related issues
Closes https://github.com/Antonboom/testifylint/issues/37
Closes https://github.com/Antonboom/testifylint/issues/38

## Testing

https://github.com/gophersbd/ormpb/blob/master/doc.go

```
$ testifylint .
/tmp/ormpb/doc.go:28:2: blank-import: avoid blank import of github.com/stretchr/testify as it does nothing
```

https://github.com/Scalingo/grafana-scalingo
```
$ testifylint ./pkg/extensions/...
/tmp/grafana-scalingo/pkg/extensions/main.go:26:2: blank-import: avoid blank import of github.com/stretchr/testify/require as it does nothing
```

### CODE REVIEW

**Comment by hendrywiranto** [comment]
Hi @Antonboom , please kindly review the PR

Also I have some questions that I think you can give inputs:
1. checker name
2. default enabled/not
3. did I use the golden template correctly?
4. I cant seem to run the unit test locally, can you help?

output from `task test`
```
Generate analyzer tests...
2023/12/20 22:44:15 [WARN] No golden file in "analyzer/testdata/src/error-as-target"
2023/12/20 22:44:15 [WARN] No golden file in "analyzer/testdata/src/require-error-fn-pattern"
2023/12/20 22:44:15 [WARN] No golden file in "analyzer/testdata/src/checkers-default/float-compare"
2023/12/20 22:44:15 [WARN] No golden file in "analyzer/testdata/src/checkers-default/go-require"
2023/12/20 22:44:15 [WARN] No golden file in "analyzer/testdata/src/checkers-default/require-error"
Test...
?       github.com/Antonboom/testifylint        [no test files]
?       github.com/Antonboom/testifylint/internal/testify       [no test files]
signal: killed
FAIL    github.com/Antonboom/testifylint/analyzer       6.041s
ok      github.com/Antonboom/testifylint/internal/analysisutil  (cached)
ok      github.com/Antonboom/testifylint/internal/checkers      (cached)
ok      github.com/Antonboom/testifylint/internal/config        (cached)
ok      github.com/Antonboom/testifylint/internal/testgen       (cached)
FAIL
task: Failed to run task "test": exit status 1
```

thank you so much!

**Comment by hendrywiranto** [comment]
hi @Antonboom have you got any chance to look at the PR? thankyou 🙇

**Comment by Antonboom** [comment]
@hendrywiranto, hi!
thank u for your job, yes, this is in my todo list

the end of the year is time of Christmas holidays, sorry 🙂 ☃️ 🎄

**Comment by hendrywiranto** [comment]
Okay Anton, sorry for nudging and enjoy your holiday !

**Comment by Antonboom** [comment]
@hendrywiranto, hi!

Please review changes from me.

> I cant seem to run the unit test locally, can you help?

Because no such packages in `testdata/src/vendor`:

<details>

```
$ task          
Tidy...
go: downloading golang.org/x/sync v0.5.0
Fmt...
Lint...
Generate analyzer tests...
2024/01/09 08:43:48 [WARN] No golden file in "analyzer/testdata/src/error-as-target"
2024/01/09 08:43:48 [WARN] No golden file in "analyzer/testdata/src/require-error-fn-pattern"
2024/01/09 08:43:49 [WARN] No golden file in "analyzer/testdata/src/checkers-default/float-compare"
2024/01/09 08:43:49 [WARN] No golden file in "analyzer/testdata/src/checkers-default/go-require"
2024/01/09 08:43:49 [WARN] No golden file in "analyzer/testdata/src/checkers-default/require-error"
Test...
?       github.com/Antonboom/testifylint        [no test files]
?       github.com/Antonboom/testifylint/internal/testify       [no test files]
src/checkers-default/useless-import/useless_import_test.go:9:2: cannot find package "github.com/stretchr/testify/http" in any of:
        /private/tmp/testifylint/analyzer/testdata/src/vendor/github.com/stretchr/testify/http (vendor tree)
        /usr/local/go/src/github.com/stretchr/testify/http (from $GOROOT)
        /private/tmp/testifylint/analyzer/testdata/src/github.com/stretchr/testify/http (from $GOPATH)
src/checkers-default/useless-import/useless_import_test.go:10:2: cannot find package "github.com/stretchr/testify/mock" in any of:
        /private/tmp/testifylint/analyzer/testdata/src/vendor/github.com/stretchr/testify/mock (vendor tree)
        /usr/local/go/src/github.com/stretchr/testify/mock (from $GOROOT)
        /private/tmp/testifylint/analyzer/testdata/src/github.com/stretchr/testify/mock (from $GOPATH)
/private/tmp/testifylint/analyzer/testdata/src/checkers-default/useless-import/useless_import_test.go:9:4: could not import github.com/stretchr/testify/http (invalid package name: "")
/private/tmp/testifylint/analyzer/testdata/src/checkers-default/useless-import/useless_import_test.go:10:4: could not import github.com/stretchr/testify/mock (invalid package name: "")
--- FAIL: TestTestifyLint_CheckersDefault (0.00s)
    --- FAIL: TestTestifyLint_CheckersDefault/useless-import (8.41s)
        analysistest.go:332: error analyzing testifylint@checkers-default/useless-import: analysis skipped due to errors in package
        analysistest.go:332: error analyzing testifylint@checkers-default/useless-import.test: analysis skipped due to errors in package
FAIL
FAIL    github.com/Antonboom/testifylint/analyzer       22.311s
ok      github.com/Antonboom/testifylint/internal/analysisutil  0.578s
ok      github.com/Antonboom/testifylint/internal/checkers      0.381s
ok      github.com/Antonboom/testifylint/internal/config        1.104s
ok      github.com/Antonboom/testifylint/internal/testgen       0.742s
FAIL
task: Failed to run task "default": exit status 1
```

</details>

**Comment by hendrywiranto** [comment]
The change looks good! made me wonder if it's better to rename the checker into `black-import` instead? wdyt?

also thanks for checking for the unit test, but I still can't run it successfully from local with the same error 😢
the frustrating part is there is no useful log on my side that shows what goes wrong

**Comment by Antonboom** [comment]
> it's better to rename the checker into black-import instead

Great idea, could I ask you to do renaming? Thanks.

> there is no useful log on my side that shows what goes wrong

Please, try 
```
go test -v ./...
```

directly, without `task`

P.S. `signal: killed` – looks very strange, what is your OS?

**Comment by Antonboom** [comment]
@hendrywiranto 

But from other side we have https://github.com/Antonboom/testifylint/blob/master/CONTRIBUTING.md#inefficient-assert.

And looks more consistent to have
- useless-import
- useless-assert

🤔

**Comment by hendrywiranto** [comment]
> But not black – blank-import

Lol sorry this is a typo on my end, didn't realize I typed black there 😆 

> And looks more consistent to have
useless-import
useless-assert

I see, just realized that.. Then I think it's okay to keep the existing name 👍

**Comment by Antonboom** [comment]
@hendrywiranto 

1) I tested the checker (did your work) on several code bases from #37 and #38 and found some uncovered and difficult to auto-removing imports variations. Auto-fixing was disabled. This is over-engineering for this checker.

2) Renamed to `blank-import`. I couldn't think of any other import that might be useless. But this name more strict and clear.

Thanks for you job, but will be more attentive 👍

**Comment by hendrywiranto** [comment]
@Antonboom 
really sorry if the work I've done is not perfect and you end up helping a lot, I'll keep in mind to test to the actual codebase when working on the next feature

thanks for the work too ! 👍

**Pull request merged**
